// Generated by scripts/build-clients.mjs. Edit packages/companion/src/client.js instead.
window.__ModuleLoader__.load({
  id: 'dsh-ssh-workspace-companion',
  factory: (require) => {
    const module = { exports: {} }
    const exports = module.exports
    exports.inject = ['sessions', 'workspaces', 'uiWorkspace']

    const BRIDGE_PROTOCOL_VERSION = 1
    const BRIDGE_CAPABILITIES = Object.freeze([
      'session/open',
      'session/create',
      'session/search',
      'session/rename',
      'session/fork',
      'workspace/create',
      'workspace/rename',
      'workspace/delete',
      'workspace/insertBefore',
      'workspace/archiveSession',
      'workspace/insertSessionBefore',
    ])
    const BRIDGE_METHODS = new Set(BRIDGE_CAPABILITIES)

    function parseHash() {
      const params = new URLSearchParams(window.location.hash.replace(/^#/, ''))
      return { token: params.get('token') || '', parent: params.get('parent') || '' }
    }

    function installEmbeddedCss() {
      document.body.setAttribute('data-dsh-remote-desktop-child', 'true')
      const style = document.createElement('style')
      style.setAttribute('data-dsh-remote-desktop-companion', '')
      style.textContent = `
        body[data-dsh-remote-desktop-child="true"] #root [class*="frame"]:has(> [class*="sidebarCol"]) > [class*="sidebarCol"] { visibility: hidden !important; pointer-events: none !important; overflow: hidden !important; }
        body[data-dsh-remote-desktop-child="true"] [class*="handle"][data-side="sidebar"] { display: none !important; }
        body[data-dsh-remote-desktop-child="true"] #root [class*="frame"]:has(> [class*="sidebarCol"]) { grid-template-columns: 0 minmax(0, 1fr) 0 !important; }
      `
      document.head.appendChild(style)
      return () => { style.remove(); document.body.removeAttribute('data-dsh-remote-desktop-child') }
    }

    function controllerSnapshot(ctx) {
      const sessions = ctx.sessions.list.getSnapshot()
      const workspaces = ctx.workspaces.list.getSnapshot()
      return {
        sessions: {
          ...sessions,
          items: (sessions.ids || Object.keys(sessions.byId || {}))
            .map(id => sessions.byId?.[id])
            .filter(Boolean),
        },
        workspaces: {
          ...workspaces,
          items: [...(workspaces.items || [])],
          archivedSessionIds: [...(workspaces.archivedSessionIds || [])],
        },
      }
    }

    function structuredError(error) {
      const code = typeof error?.code === 'string' ? error.code : 'remote_desktop_bridge_failed'
      const message = error instanceof Error ? error.message : String(error)
      return { code, message }
    }

    async function waitUntilCurrent(ctx, sessionId, signal) {
      signal.throwIfAborted()
      ctx.uiWorkspace.openSession(sessionId)
      await ctx.sessions.using(sessionId, { source: 'controllerOperation', signal }, async reference => {
        await reference.ready
        signal.throwIfAborted()
        const owners = ctx.sessions.retainInfo(sessionId).getSnapshot().retainedBy
        if ((owners.mainView || 0) === 0) throw new Error('session open superseded')
      })
    }

    async function invoke(ctx, method, payload, signal) {
      if (!BRIDGE_METHODS.has(method)) throw new Error(`unsupported remote desktop bridge method ${String(method)}`)
      switch (method) {
        case 'session/open': await waitUntilCurrent(ctx, payload.sessionId, signal); return { sessionId: payload.sessionId }
        case 'session/create': return { sessionId: await ctx.sessions.create({ workspaceId: payload.workspaceId }) }
        case 'session/search': {
          const result = await ctx.sessions.search(String(payload.query || ''), signal)
          if (!result.ok) throw new Error(result.error.message)
          return result.value
        }
        case 'session/rename': {
          return ctx.sessions.using(payload.sessionId, { source: 'controllerOperation', signal }, async reference => {
            const binding = await reference.ready
            const result = await binding.session.rename(payload.title)
            if (!result.ok) throw new Error(result.error.message)
            return result.value
          })
        }
        case 'session/fork': {
          const sessionId = await ctx.sessions.fork({ sessionId: payload.sessionId, increaseTitle: true })
          return { sessionId }
        }
        case 'workspace/create': return { workspace: await ctx.workspaces.create({ path: payload.path }) }
        case 'workspace/rename': return { workspace: await ctx.workspaces.rename(payload.workspaceId, payload.title) }
        case 'workspace/delete': await ctx.workspaces.delete(payload.workspaceId); return {}
        case 'workspace/insertBefore': await ctx.workspaces.insertBefore(payload.workspaceId, payload.beforeWorkspaceId); return {}
        case 'workspace/archiveSession': await ctx.workspaces.archiveSession(payload.sessionId); return {}
        case 'workspace/insertSessionBefore':
          return { workspace: await ctx.workspaces.insertSessionBefore(payload.workspaceId, payload.sessionId, payload.beforeSessionId) }
        default: throw new Error(`unsupported remote desktop bridge method ${String(method)}`)
      }
    }

    exports.apply = function apply(ctx) {
      const marker = new URLSearchParams(window.location.search).get('dshRemoteDesktop')
      const { token, parent } = parseHash()
      if (marker !== '1' || token === '' || parent === '') return
      ctx.effect(() => {
        const disposeCss = installEmbeddedCss()
        let channel
        let channelCleanup = () => {}
        let openController
        let announceTimer

        const announceListening = () => {
          window.parent.postMessage({
            type: 'dsh-remote-desktop/bridge-listening',
            protocolVersion: BRIDGE_PROTOCOL_VERSION,
            sourceToken: token,
          }, parent)
        }

        const attach = (port) => {
          window.clearInterval(announceTimer)
          channelCleanup()
          channel = port
          const generation = globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`
          let revision = 0
          let queued = false
          const publishBaseline = () => {
            if (queued) return
            queued = true
            queueMicrotask(() => {
              queued = false
              if (channel !== port) return
              revision += 1
              port.postMessage({
                type: 'dsh-remote-desktop/state-baseline',
                protocolVersion: BRIDGE_PROTOCOL_VERSION,
                sourceToken: token,
                generation,
                revision,
                snapshot: controllerSnapshot(ctx),
              })
            })
          }
          const disposeSessions = ctx.sessions.list.subscribe(publishBaseline)
          const disposeWorkspaces = ctx.workspaces.list.subscribe(publishBaseline)
          port.onmessage = (event) => {
            const data = event.data
            if (data?.sourceToken !== token || data.protocolVersion !== BRIDGE_PROTOCOL_VERSION) return
            if (data.type === 'dsh-remote-desktop/state-resync') {
              publishBaseline()
              return
            }
            if (data.type !== 'dsh-remote-desktop/request') return
            if (typeof data.requestId !== 'string' || typeof data.method !== 'string') return
            if (!BRIDGE_METHODS.has(data.method)) {
              port.postMessage({
                type: 'dsh-remote-desktop/result', protocolVersion: BRIDGE_PROTOCOL_VERSION,
                sourceToken: token, requestId: data.requestId, ok: false,
                error: { code: 'unsupported_method', message: `unsupported remote desktop bridge method ${data.method}` },
              })
              return
            }
            if (data.method === 'session/open') {
              openController?.abort(new Error('session open superseded'))
              openController = new AbortController()
            }
            const signal = data.method === 'session/open' ? openController.signal : AbortSignal.timeout(30_000)
            void invoke(ctx, data.method, data.payload || {}, signal).then((value) => {
              port.postMessage({
                type: 'dsh-remote-desktop/result', protocolVersion: BRIDGE_PROTOCOL_VERSION,
                sourceToken: token, requestId: data.requestId, ok: true, value,
              })
            }).catch((error) => {
              port.postMessage({
                type: 'dsh-remote-desktop/result', protocolVersion: BRIDGE_PROTOCOL_VERSION,
                sourceToken: token, requestId: data.requestId, ok: false, error: structuredError(error),
              })
            })
          }
          port.start?.()
          port.postMessage({
            type: 'dsh-remote-desktop/ready',
            protocolVersion: BRIDGE_PROTOCOL_VERSION,
            sourceToken: token,
            generation,
            capabilities: BRIDGE_CAPABILITIES,
          })
          publishBaseline()
          channelCleanup = () => {
            disposeWorkspaces()
            disposeSessions()
            port.close()
          }
        }

        const onMessage = (event) => {
          if (event.origin !== parent || event.source !== window.parent) return
          const data = event.data
          if (data?.type !== 'dsh-remote-desktop/connect'
            || data.protocolVersion !== BRIDGE_PROTOCOL_VERSION
            || data.sourceToken !== token) return
          const port = event.ports?.[0]
          if (port === undefined) return
          attach(port)
        }
        window.addEventListener('message', onMessage)
        announceListening()
        announceTimer = window.setInterval(announceListening, 500)
        return () => {
          window.clearInterval(announceTimer)
          openController?.abort(new Error('remote desktop companion disposed'))
          channelCleanup()
          window.removeEventListener('message', onMessage)
          disposeCss()
        }
      }, 'dsh-remote-desktop-companion: iframe bridge')
    }
    return module.exports
  },
})
